// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 */

package mlmodelprovision

import (
	"encoding/json"
	"net/http"
	mlmodelprovisionAPI "nwdaf-otel/generated/mlmodelprovision"
	"strings"
)

// SubscriptionsCollectionAPIController binds http requests to an api service and writes the service results to the http response
type SubscriptionsCollectionAPIController struct {
	service      mlmodelprovisionAPI.SubscriptionsCollectionAPIServicer
	errorHandler mlmodelprovisionAPI.ErrorHandler
}

// SubscriptionsCollectionAPIOption for how the controller is set up.
type SubscriptionsCollectionAPIOption func(*SubscriptionsCollectionAPIController)

// WithSubscriptionsCollectionAPIErrorHandler inject ErrorHandler into controller
func WithSubscriptionsCollectionAPIErrorHandler(h mlmodelprovisionAPI.ErrorHandler) SubscriptionsCollectionAPIOption {
	return func(c *SubscriptionsCollectionAPIController) {
		c.errorHandler = h
	}
}

// NewSubscriptionsCollectionAPIController creates a default api controller
func NewSubscriptionsCollectionAPIController(s mlmodelprovisionAPI.SubscriptionsCollectionAPIServicer, opts ...SubscriptionsCollectionAPIOption) *SubscriptionsCollectionAPIController {
	controller := &SubscriptionsCollectionAPIController{
		service:      s,
		errorHandler: mlmodelprovisionAPI.DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the SubscriptionsCollectionAPIController
func (c *SubscriptionsCollectionAPIController) Routes() mlmodelprovisionAPI.Routes {
	return mlmodelprovisionAPI.Routes{
		"CreateNWDAFMLModelProvisionSubcription": mlmodelprovisionAPI.Route{
			"CreateNWDAFMLModelProvisionSubcription",
			strings.ToUpper("Post"),
			"/nnwdaf-mlmodelprovision/v1/subscriptions",
			c.CreateNWDAFMLModelProvisionSubcription,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the SubscriptionsCollectionAPIController
func (c *SubscriptionsCollectionAPIController) OrderedRoutes() []mlmodelprovisionAPI.Route {
	return []mlmodelprovisionAPI.Route{
		mlmodelprovisionAPI.Route{
			"CreateNWDAFMLModelProvisionSubcription",
			strings.ToUpper("Post"),
			"/nnwdaf-mlmodelprovision/v1/subscriptions",
			c.CreateNWDAFMLModelProvisionSubcription,
		},
	}
}



// CreateNWDAFMLModelProvisionSubcription - Create a new Individual NWDAF ML Model Provision Subscription resource.
func (c *SubscriptionsCollectionAPIController) CreateNWDAFMLModelProvisionSubcription(w http.ResponseWriter, r *http.Request) {
	var nwdafMlModelProvSubscParam mlmodelprovisionAPI.NwdafMlModelProvSubsc
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&nwdafMlModelProvSubscParam); err != nil {
		c.errorHandler(w, r, &mlmodelprovisionAPI.ParsingError{Err: err}, nil)
		return
	}
	if err := mlmodelprovisionAPI.AssertNwdafMlModelProvSubscRequired(nwdafMlModelProvSubscParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := mlmodelprovisionAPI.AssertNwdafMlModelProvSubscConstraints(nwdafMlModelProvSubscParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateNWDAFMLModelProvisionSubcription(r.Context(), nwdafMlModelProvSubscParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = mlmodelprovisionAPI.EncodeJSONResponse(result.Body, &result.Code, w)
}
