apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:
    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m
    compactor:
      compaction:
        compacted_block_retention: 24h
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
    # -- Instead of using OTEL connector(s), use already Grafana competible Tempo metric processors
    metricsGenerator:
      enabled: true
      registry:
        external_labels:
          source: tempo
      config:
        storage:
          remote_write:
            - url: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc.cluster.local:9090"
              send_exemplars: true
      global_overrides:
        metrics_generator_processors: [ service-graphs, span-metrics ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.8.2
          args: ["-config.file=/etc/tempo/tempo.yaml"]
          ports:
            - containerPort: 3100 #Grafana GETS traces from here
            - containerPort: 4317 #OTEL gRPC
            - containerPort: 4318 #OTEL HTTP
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
            - name: tempo-data
              mountPath: /var/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
    - name: http
      port: 3100 # Grafana scraps this port
      targetPort: 3100
    - name: otlp-grpc
      port: 4317 # receiver
      targetPort: 4317
    - name: otlp-http
      port: 4318 # receiver
      targetPort: 4318
  selector:
    app: tempo