apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    stream_over_http_enabled: true
    multitenancy_enabled: false
    usage_report:
      reporting_enabled: false
    server:
      http_listen_port: 3200
      log_level: debug
    distributor:
      log_received_spans:
        enabled: true
      log_discarded_spans:
        enabled: true
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
    compactor:
      compaction:
        compacted_block_retention: 24h
    querier:
      frontend_worker:
        frontend_address: "127.0.0.1:9095"
    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal # where to store the wal locally
        local:
          path: /var/tempo/blocks # where traces are stored in blocks, search backend keeps metadata pointing to blocks
    metrics_generator:
      ring:
        kvstore:
          store: inmemory

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.8.2
          args: ["-config.file=/etc/tempo/tempo.yaml"]
          ports:
            - containerPort: 3200 #Grafana GETS traces from here
            - containerPort: 4317 #OTEL gRPC
            - containerPort: 4318 #OTEL HTTP
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
            - name: tempo-data
              mountPath: /var/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
    - name: http
      port: 3200 # Grafana scraps this port
      targetPort: 3200
    - name: otlp-grpc
      port: 4317 # receiver
      targetPort: 4317
    - name: otlp-http
      port: 4318 # receiver
      targetPort: 4318
  selector:
    app: tempo